server.port: 8080

management.endpoints.web.exposure.include: '*'

resilience4j.circuitbreaker.instances:
  helloApi:
    failure-rate-threshold: 50
    permitted-number-of-calls-in-half-open-state: 5
    sliding-window-type: COUNT_BASED
    sliding-window-size: 10
    minimum-number-of-calls: 10
    wait-duration-in-open-state: 3s
    automatic-transition-from-open-to-half-open-enabled: true