server.port: 8080

management.endpoints.web.exposure.include: '*'

resilience4j.circuitbreaker.instances:
  helloApi:
    failure-rate-threshold: 70
    wait-duration-in-open-state: 1000
    ring-buffer-size-in-closed-state: 2
    ring-buffer-size-in-half-open-state: 1
resilience4j:
  circuitbreaker:
    instances:
      helloApi:

